name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate_rss.py

      - name: Commit RSS feed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add police_incidents.rss
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
